import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavbarMenu } from "@/components/NavbarMenu";
import SessionAuthProvider from "@/context/SessionAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <SessionAuthProvider>
          <NavbarMenu />
          <div className="h-[calc(100vh+30rem)] container mx-auto">
            {children}
          </div>
        </SessionAuthProvider>
      </body>
    </html>
  );
}
